### ISSUE TITLE
Wikissä rikkinäinen linkki

### ISSUE THREAD

**Issue by cxcorp** [mluukkai/OTM2016#2]
Wikissä sivulla [Viikon 4 paikanpaalla tehtavat](https://github.com/mluukkai/OTM2016/wiki/Viikon-4-paikanpaalla-tehtavat) on linkki:

> Etsikää luokkakandidaatit [luennolla 4](https://github.com/mluukkai/OTM2016/wiki/(../raw/master/luennot/luento4.pdf?raw=true)) esitettyä käsiteanalyysiä käyttäen ...

Linkki osoittaa osoitteeseen `https://github.com/mluukkai/OTM2016/wiki/(../raw/master/luennot/luento4.pdf?raw=true)`, mutta epäilen, että sen pitäisi olla `https://github.com/mluukkai/OTM2016/raw/master/luennot/luento4.pdf?raw=true`.

**Comment by mluukkai** [comment]
kiitokset, korjattu!
